#!/bin/sh
# cd to dir && run in wine in another X Display
gm 1
if [ ! "$1" ]; then
   echo "Usage : xwine [gameDir] [exe]"
   exit
fi
if [ ! "$2" ]; then
   echo "Usage : xwine [gameDir] [exe]"
   exit
fi

echo "01"
X :2 -ac -terminate & nvidia-settings --load-config-only
echo "02"
sleep 10
DISPLAY=:2
cd "$1"
WINEDEBUG=-all wine "$2" $3
echo "03"
